name = "backend"
main = "src/index.ts"
compatibility_date = "2025-01-01"

compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "loutine-dev"
database_id = "31442ac4-9999-494d-b9f4-625757b2742f"

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1
